spring:
  application:
    name: player-service
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/player?user=player&password=secured"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      "hibernate.jdbc.lob.non_contextual_creation": true
    database-platform: org.hibernate.dialect.ProgressDialect
    hibernate:
      ddl-auto: update

server:
  port: ${PLAYER_SERVICE_PORT:8801}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${spring.application.name}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

management:
  endpoint:
    health:
      group:
        liveness:
          include: "livenessProbe,db"
        readiness:
          include: "livenessProbe,readinessProbe,db"