spring:
  application:
    name: eureka
  main:
    banner-mode: off

server:
  port: ${EUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


error:
  whitelabel:
    enabled: false
