spring:
  application:
    name: team-service
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/team?user=team&password=secured"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      "hibernate.jdbc.lob.non_contextual_creation": true
    database-platform: org.hibernate.dialect.ProgressDialect
    hibernate:
      ddl-auto: update

server:
  port: ${TEAM_SERVICE_PORT:8802}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://localhost:8761/eureka}

management:
  endpoint:
    health:
      group:
        liveness:
          include: "livenessProbe,db"
        readiness:
          include: "livenessProbe,readinessProbe,db"