apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "prod"
---

apiVersion: "v1"
kind: "Service"
metadata:
  name: "payday-service"
  namespace: "prod"
  labels:
    app: "payday"
spec:
  ports:
    - name: "web"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
  selector:
    app: "payday"
  type: "NodePort"
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "payday-deployment"
  namespace: "prod"
  labels:
    app: "payday"
    tier: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "payday"
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "payday"
    spec:
      containers:
        - name: "payday"
          image: "198.168.0.2:30006/payday-trade:1.0.1"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "prod"
            - name: "SPRING_DATASOURCE_URL"
              value: "jdbc:postgresql://postgres-service.prod.svc.cluster.local:5432/payday?user=postgres&password=secured2019"
          ports:
            - containerPort: 8080
              name: "http"
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            initialDelaySeconds: 60
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
      imagePullSecrets:
        - name: "nexus-docker-registry"
      restartPolicy: "Always"

