apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "prod"
---

apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "postgres-pvc"
  namespace: "prod"
  labels:
    app: "postgres"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
---

apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres-service"
  namespace: "prod"
  labels:
    app: "postgres"
spec:
  ports:
    - name: "web"
      port: 5432
      protocol: "TCP"
      targetPort: 5432
  selector:
    app: "postgres"
  type: "NodePort"
---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres-deployment"
  namespace: "prod"
  labels:
    app: "postgres"
    tier: "database"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "postgres"
    spec:
      containers:
        - name: "postgres"
          image: "postgres:12"
          env:
            - name: "POSTGRES_USER"
              value: "postgres"
            - name: "POSTGRES_PASSWORD"
              value: "secured2019"
            - name: "POSTGRES_DB"
              value: "payday"
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "data"
      volumes:
        - name: "data"
          persistentVolumeClaim:
            claimName: "postgres-pvc"
